[project]
drom-version = "0.1"

[project]
authors = ["Julien Blond <julien.blond@gmail.com>"]
ci-systems = ["ubuntu-latest", "macos-latest", "windows-latest"]
copyright = "Julien Blond <julien.blond@gmail.com>"
edition = "4.10.0"
github-organization = "Ninjapouet"
homepage = "https://github.com/Ninjapouet/clim"
license = "LGPL2"
min-edition = "4.07.0"
name = "clim"
synopsis = "The clim project"
version = "1.0.0"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."

[project]
description = """This is the description
of the clim OCaml project
"""

[project]
skip = [".gitignore", "test", "src/clim-ppx/main.ml", "src/clim/main.ml"]

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[tools]
dune = "2.7"

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
[fields]
# ...

[[package]]
dir = "src/clim"
# edit 'src/clim/package.toml' for package-specific options

[[package]]
dir = "src/clim-ppx"
# edit 'src/clim-ppx/package.toml' for package-specific options

